// Generated by scripts/catalog/fetch-photos.mjs — do not edit by hand.
export const catalogPhotos: Record<string, number[]> = {
  'monstera-deliciosa': [require('../../assets/catalog/photos/monstera-deliciosa-1.webp')],
  'epipremnum-aureum': [require('../../assets/catalog/photos/epipremnum-aureum-1.webp')],
  'dracaena-trifasciata': [require('../../assets/catalog/photos/dracaena-trifasciata-1.webp')],
  'zamioculcas-zamiifolia': [require('../../assets/catalog/photos/zamioculcas-zamiifolia-1.webp')],
  'ficus-lyrata': [require('../../assets/catalog/photos/ficus-lyrata-1.webp')],
  'ficus-elastica': [require('../../assets/catalog/photos/ficus-elastica-1.webp')],
  'spathiphyllum-wallisii': [require('../../assets/catalog/photos/spathiphyllum-wallisii-1.webp')],
  'chlorophytum-comosum': [require('../../assets/catalog/photos/chlorophytum-comosum-1.webp')],
  'pilea-peperomioides': [require('../../assets/catalog/photos/pilea-peperomioides-1.webp')],
  'goeppertia-orbifolia': [require('../../assets/catalog/photos/goeppertia-orbifolia-1.webp')],
  'aloe-vera': [require('../../assets/catalog/photos/aloe-vera-1.webp')],
  'strelitzia-reginae': [require('../../assets/catalog/photos/strelitzia-reginae-1.webp')],
  'philodendron-hederaceum': [
    require('../../assets/catalog/photos/philodendron-hederaceum-1.webp'),
  ],
  phalaenopsis: [require('../../assets/catalog/photos/phalaenopsis-1.webp')],
  'hoya-carnosa': [require('../../assets/catalog/photos/hoya-carnosa-1.webp')],
  'peperomia-obtusifolia': [require('../../assets/catalog/photos/peperomia-obtusifolia-1.webp')],
};
