// Fetches one freely-licensed example photo per catalog plant from Wikimedia Commons,
// resizes it to WebP, records author/license/source in catalog.json and regenerates
// src/catalog/photos.generated.ts.
//
// Strategy: use the taxon's lead image on English Wikipedia (curated, representative),
// then verify its licence on Commons. Falls back to a Commons search.
//
// Usage: node scripts/catalog/fetch-photos.mjs [--force]
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

import sharp from 'sharp';

const ROOT = new URL('../../', import.meta.url);
const CATALOG = new URL('assets/catalog/catalog.json', ROOT);
const PHOTOS_DIR = new URL('assets/catalog/photos/', ROOT);
const GENERATED = new URL('src/catalog/photos.generated.ts', ROOT);
const UA = 'plant-app-catalog-builder/0.1 (personal offline houseplant app; build-time only)';
const FORCE = process.argv.includes('--force');

const WIDTH = 600;
const QUALITY = 75;

// Free licences only. NC / ND variants are rejected.
const ALLOWED = [/^cc0/i, /^public domain/i, /^pd/i, /^cc by(-sa)? \d/i, /^cc-by(-sa)?-\d/i];
const isAllowed = (lic) => ALLOWED.some((re) => re.test(lic)) && !/[-\s](nc|nd)\b/i.test(lic);

const stripHtml = (s) =>
  s
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&#039;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, ' ')
    .trim();

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function get(url) {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (res.status === 429 && attempt < 5) {
      const wait = Number(res.headers.get('retry-after')) * 1000 || 2000 * 2 ** attempt;
      await sleep(wait);
      continue;
    }
    if (!res.ok) throw new Error(`${res.status} ${url}`);
    return res;
  }
}

async function api(base, params) {
  const url = `${base}?${new URLSearchParams({ format: 'json', formatversion: '2', ...params })}`;
  await sleep(700);
  return (await get(url)).json();
}

async function leadImage(latin) {
  const data = await api('https://en.wikipedia.org/w/api.php', {
    action: 'query',
    titles: latin,
    redirects: '1',
    prop: 'pageimages',
    piprop: 'name',
  });
  return data.query?.pages?.[0]?.pageimage ?? null;
}

async function searchCommons(latin) {
  const data = await api('https://commons.wikimedia.org/w/api.php', {
    action: 'query',
    list: 'search',
    srsearch: `${latin} filetype:bitmap`,
    srnamespace: '6',
    srlimit: '10',
  });
  return (data.query?.search ?? []).map((r) => r.title.replace(/^File:/, ''));
}

async function fileInfo(name) {
  const data = await api('https://commons.wikimedia.org/w/api.php', {
    action: 'query',
    titles: `File:${name}`,
    prop: 'imageinfo',
    iiprop: 'url|extmetadata|size|mime',
    iiurlwidth: String(WIDTH * 2),
  });
  const page = data.query?.pages?.[0];
  const ii = page?.imageinfo?.[0];
  if (!ii || page.missing) return null;
  const meta = ii.extmetadata ?? {};
  return {
    thumb: ii.thumburl,
    width: ii.width,
    height: ii.height,
    mime: ii.mime,
    license: meta.LicenseShortName?.value ?? '',
    author: stripHtml(meta.Artist?.value ?? meta.Attribution?.value ?? ''),
    source_url: ii.descriptionurl,
  };
}

function usable(info) {
  if (!info || !info.thumb) return false;
  if (!/jpeg|png|webp/.test(info.mime)) return false;
  if (info.width < WIDTH) return false;
  const ratio = info.width / info.height;
  const needsAuthor = !/^(cc0|public domain|pd)/i.test(info.license);
  return (
    ratio > 0.6 && ratio < 1.8 && isAllowed(info.license) && (!needsAuthor || info.author !== '')
  );
}

async function pickPhoto(latin) {
  const lead = await leadImage(latin);
  if (lead) {
    const info = await fileInfo(lead);
    if (usable(info)) return info;
    console.log(`  lead image rejected (${info?.license ?? 'no info'})`);
  }
  for (const name of await searchCommons(latin)) {
    const info = await fileInfo(name);
    if (usable(info)) return info;
  }
  return null;
}

async function download(url, dest) {
  const res = await get(url);
  const buf = Buffer.from(await res.arrayBuffer());
  const out = await sharp(buf)
    .rotate()
    .resize({ width: WIDTH, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toBuffer();
  writeFileSync(dest, out);
  return out.length;
}

function writeGenerated(plants) {
  const lines = plants
    .filter((p) => p.photos.length > 0)
    .map(
      (p) =>
        `  '${p.id}': [${p.photos.map((ph) => `require('../../assets/catalog/photos/${ph.file}')`).join(', ')}],`,
    );
  writeFileSync(
    GENERATED,
    `// Generated by scripts/catalog/fetch-photos.mjs — do not edit by hand.\nexport const catalogPhotos: Record<string, number[]> = {\n${lines.join('\n')}\n};\n`,
  );
}

async function main() {
  mkdirSync(PHOTOS_DIR, { recursive: true });
  const catalog = JSON.parse(readFileSync(CATALOG, 'utf8'));
  let total = 0;
  for (const plant of catalog.plants) {
    const file = `${plant.id}-1.webp`;
    if (!FORCE && plant.photos.length > 0 && existsSync(new URL(file, PHOTOS_DIR))) {
      console.log(`= ${plant.id} (kept)`);
      continue;
    }
    console.log(`… ${plant.id}`);
    try {
      const info = await pickPhoto(plant.latin_name);
      if (!info) {
        console.log('  no suitable free photo found');
        plant.photos = [];
        continue;
      }
      const size = await download(info.thumb, new URL(file, PHOTOS_DIR));
      total += size;
      plant.photos = [
        {
          file,
          author: info.author || 'Domaine public',
          license: info.license,
          source_url: info.source_url,
        },
      ];
      console.log(`  ✓ ${info.license} — ${info.author} (${Math.round(size / 1024)} Ko)`);
    } catch (e) {
      console.log(`  ✗ ${e.message}`);
    }
    await new Promise((r) => setTimeout(r, 300));
  }
  writeFileSync(CATALOG, JSON.stringify(catalog, null, 2) + '\n');
  writeGenerated(catalog.plants);
  console.log(`Done. Downloaded ${Math.round(total / 1024)} Ko.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
