// Writes the first draft catalog batch (data_status: 'draft', to be reviewed).
// Usage: node scripts/catalog/seed-draft.mjs
import { writeFileSync } from 'node:fs';

const GEN = { name: 'À relire' };
const ASPCA = {
  name: 'ASPCA — Toxic and Non-Toxic Plants (à vérifier)',
  url: 'https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants',
};

const p = (o) => ({
  status: 'active',
  data_status: 'draft',
  photos: [],
  problems: [],
  pet_toxic_note_fr: null,
  ...o,
  sources: o.pet_toxic === 'unknown' ? [GEN] : [GEN, ASPCA],
});

const plants = [
  p({
    id: 'monstera-deliciosa',
    latin_name: 'Monstera deliciosa',
    common_names_fr: ['Monstera', 'Faux philodendron'],
    common_names_en: ['Swiss cheese plant'],
    family: 'Araceae',
    light: 'bright_indirect',
    water_every_days_summer: 7,
    water_every_days_winter: 14,
    water_notes_fr: 'Laisser sécher les 3 premiers cm de terreau entre deux arrosages.',
    humidity: 'medium',
    temp_min_c: 15,
    temp_max_c: 30,
    soil_fr: 'Terreau pour plantes vertes allégé avec écorce et perlite.',
    fertilize_fr: 'Toutes les 3 semaines d’avril à septembre.',
    fertilize_every_days: 21,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Irritation de la bouche et vomissements.',
    difficulty: 'easy',
    tips_fr:
      'Lui offrir un tuteur en mousse pour qu’elle grimpe et fasse de plus grandes feuilles découpées.',
    problems: [
      {
        symptom_fr: 'Feuilles jaunes',
        cause_fr: 'Excès d’arrosage',
        fix_fr: 'Espacer les arrosages, vérifier le drainage.',
      },
      {
        symptom_fr: 'Feuilles sans découpes',
        cause_fr: 'Manque de lumière',
        fix_fr: 'Rapprocher d’une fenêtre lumineuse.',
      },
    ],
  }),
  p({
    id: 'epipremnum-aureum',
    latin_name: 'Epipremnum aureum',
    common_names_fr: ['Pothos', 'Lierre du diable'],
    common_names_en: ['Golden pothos', 'Devil’s ivy'],
    family: 'Araceae',
    light: 'medium',
    water_every_days_summer: 7,
    water_every_days_winter: 12,
    water_notes_fr: 'Arroser quand la moitié supérieure du pot est sèche.',
    humidity: 'medium',
    temp_min_c: 15,
    temp_max_c: 30,
    soil_fr: 'Terreau universel bien drainé.',
    fertilize_fr: 'Une fois par mois au printemps et en été.',
    fertilize_every_days: 30,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Irritation buccale, salivation, vomissements.',
    difficulty: 'easy',
    tips_fr: 'Se bouture très facilement dans un verre d’eau. Tolère bien la mi-ombre.',
    problems: [
      {
        symptom_fr: 'Tiges longues et dégarnies',
        cause_fr: 'Manque de lumière',
        fix_fr: 'Rapprocher de la lumière et tailler pour densifier.',
      },
    ],
  }),
  p({
    id: 'dracaena-trifasciata',
    latin_name: 'Dracaena trifasciata',
    common_names_fr: ['Sansevieria', 'Langue de belle-mère'],
    common_names_en: ['Snake plant'],
    family: 'Asparagaceae',
    light: 'low',
    water_every_days_summer: 14,
    water_every_days_winter: 30,
    water_notes_fr: 'Laisser sécher complètement le terreau. Éviter l’eau au cœur de la rosette.',
    humidity: 'low',
    temp_min_c: 12,
    temp_max_c: 32,
    soil_fr: 'Mélange pour cactées et succulentes.',
    fertilize_fr: 'Deux ou trois fois entre avril et septembre.',
    fertilize_every_days: 60,
    repot_every_years: 3,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Troubles digestifs.',
    difficulty: 'easy',
    tips_fr: 'Presque increvable : l’excès d’eau est son seul vrai ennemi.',
    problems: [
      {
        symptom_fr: 'Base molle et brune',
        cause_fr: 'Pourriture due à l’excès d’eau',
        fix_fr: 'Couper les parties atteintes, rempoter au sec.',
      },
    ],
  }),
  p({
    id: 'zamioculcas-zamiifolia',
    latin_name: 'Zamioculcas zamiifolia',
    common_names_fr: ['Zamioculcas', 'Plante ZZ'],
    common_names_en: ['ZZ plant'],
    family: 'Araceae',
    light: 'low',
    water_every_days_summer: 14,
    water_every_days_winter: 28,
    water_notes_fr: 'Arroser seulement quand le terreau est sec sur toute la hauteur.',
    humidity: 'low',
    temp_min_c: 15,
    temp_max_c: 30,
    soil_fr: 'Terreau drainant avec un tiers de sable ou de perlite.',
    fertilize_fr: 'Une fois par mois au printemps et en été, à demi-dose.',
    fertilize_every_days: 30,
    repot_every_years: 3,
    pet_toxic: 'unknown',
    difficulty: 'easy',
    tips_fr: 'Ses rhizomes stockent l’eau : il supporte très bien les oublis.',
  }),
  p({
    id: 'ficus-lyrata',
    latin_name: 'Ficus lyrata',
    common_names_fr: ['Figuier lyre'],
    common_names_en: ['Fiddle-leaf fig'],
    family: 'Moraceae',
    light: 'bright_indirect',
    water_every_days_summer: 7,
    water_every_days_winter: 12,
    water_notes_fr: 'Arroser copieusement puis laisser sécher les 5 premiers cm.',
    humidity: 'medium',
    temp_min_c: 16,
    temp_max_c: 28,
    soil_fr: 'Terreau pour plantes vertes bien drainé.',
    fertilize_fr: 'Toutes les 3 semaines d’avril à septembre.',
    fertilize_every_days: 21,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Sève irritante.',
    difficulty: 'hard',
    tips_fr:
      'Déteste être déplacé et les courants d’air : choisir sa place une bonne fois pour toutes.',
    problems: [
      {
        symptom_fr: 'Taches brunes au centre des feuilles',
        cause_fr: 'Excès d’eau',
        fix_fr: 'Laisser sécher davantage entre les arrosages.',
      },
      {
        symptom_fr: 'Chute de feuilles',
        cause_fr: 'Changement de place ou courant d’air',
        fix_fr: 'Stabiliser l’emplacement, éloigner des portes.',
      },
    ],
  }),
  p({
    id: 'ficus-elastica',
    latin_name: 'Ficus elastica',
    common_names_fr: ['Caoutchouc', 'Ficus élastique'],
    common_names_en: ['Rubber plant'],
    family: 'Moraceae',
    light: 'bright_indirect',
    water_every_days_summer: 8,
    water_every_days_winter: 14,
    water_notes_fr: 'Laisser sécher la moitié supérieure du terreau.',
    humidity: 'medium',
    temp_min_c: 15,
    temp_max_c: 30,
    soil_fr: 'Terreau pour plantes vertes.',
    fertilize_fr: 'Une fois par mois au printemps et en été.',
    fertilize_every_days: 30,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Sève irritante pour la peau et le système digestif.',
    difficulty: 'easy',
    tips_fr:
      'Dépoussiérer les grandes feuilles avec un chiffon humide pour qu’elles restent brillantes.',
  }),
  p({
    id: 'spathiphyllum-wallisii',
    latin_name: 'Spathiphyllum wallisii',
    common_names_fr: ['Spathiphyllum', 'Fleur de lune'],
    common_names_en: ['Peace lily'],
    family: 'Araceae',
    light: 'medium',
    water_every_days_summer: 5,
    water_every_days_winter: 9,
    water_notes_fr:
      'Garder le terreau légèrement humide. Les feuilles s’affaissent quand elle a soif.',
    humidity: 'high',
    temp_min_c: 16,
    temp_max_c: 28,
    soil_fr: 'Terreau riche qui retient un peu l’humidité.',
    fertilize_fr: 'Toutes les 3 semaines au printemps et en été.',
    fertilize_every_days: 21,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Irritation buccale, salivation.',
    difficulty: 'easy',
    tips_fr:
      'Vaporiser régulièrement le feuillage. Elle se redresse en quelques heures après un arrosage.',
  }),
  p({
    id: 'chlorophytum-comosum',
    latin_name: 'Chlorophytum comosum',
    common_names_fr: ['Plante araignée', 'Phalangère'],
    common_names_en: ['Spider plant'],
    family: 'Asparagaceae',
    light: 'medium',
    water_every_days_summer: 5,
    water_every_days_winter: 10,
    water_notes_fr: 'Arroser quand la surface est sèche.',
    humidity: 'medium',
    temp_min_c: 10,
    temp_max_c: 30,
    soil_fr: 'Terreau universel.',
    fertilize_fr: 'Toutes les 3 semaines au printemps et en été.',
    fertilize_every_days: 21,
    repot_every_years: 2,
    pet_toxic: 'no',
    difficulty: 'easy',
    tips_fr: 'Les petits rejets suspendus se repiquent facilement pour faire de nouvelles plantes.',
    problems: [
      {
        symptom_fr: 'Pointes des feuilles brunes',
        cause_fr: 'Air sec ou eau calcaire',
        fix_fr: 'Arroser à l’eau de pluie ou reposée.',
      },
    ],
  }),
  p({
    id: 'pilea-peperomioides',
    latin_name: 'Pilea peperomioides',
    common_names_fr: ['Pilea', 'Plante à monnaie chinoise'],
    common_names_en: ['Chinese money plant'],
    family: 'Urticaceae',
    light: 'bright_indirect',
    water_every_days_summer: 6,
    water_every_days_winter: 12,
    water_notes_fr: 'Laisser sécher les 2-3 premiers cm.',
    humidity: 'medium',
    temp_min_c: 12,
    temp_max_c: 28,
    soil_fr: 'Terreau universel avec perlite.',
    fertilize_fr: 'Une fois par mois au printemps et en été.',
    fertilize_every_days: 30,
    repot_every_years: 2,
    pet_toxic: 'unknown',
    difficulty: 'easy',
    tips_fr: 'Tourner le pot d’un quart de tour chaque semaine pour qu’elle pousse droite.',
  }),
  p({
    id: 'goeppertia-orbifolia',
    latin_name: 'Goeppertia orbifolia',
    common_names_fr: ['Calathea orbifolia'],
    common_names_en: ['Prayer plant'],
    family: 'Marantaceae',
    light: 'medium',
    water_every_days_summer: 5,
    water_every_days_winter: 8,
    water_notes_fr: 'Garder le terreau frais sans être détrempé. Eau non calcaire.',
    humidity: 'high',
    temp_min_c: 18,
    temp_max_c: 27,
    soil_fr: 'Terreau léger et riche, type plantes vertes.',
    fertilize_fr: 'Toutes les 4 semaines au printemps et en été, à demi-dose.',
    fertilize_every_days: 28,
    repot_every_years: 2,
    pet_toxic: 'no',
    difficulty: 'hard',
    tips_fr: 'Aime l’humidité d’une salle de bain lumineuse. Ses feuilles se replient le soir.',
    problems: [
      {
        symptom_fr: 'Bords des feuilles qui grillent',
        cause_fr: 'Air trop sec ou eau calcaire',
        fix_fr: 'Humidifier l’air, utiliser de l’eau de pluie.',
      },
    ],
  }),
  p({
    id: 'aloe-vera',
    latin_name: 'Aloe vera',
    common_names_fr: ['Aloe vera'],
    common_names_en: ['Aloe vera'],
    family: 'Asphodelaceae',
    light: 'direct',
    water_every_days_summer: 14,
    water_every_days_winter: 30,
    water_notes_fr: 'Arroser seulement quand le terreau est totalement sec.',
    humidity: 'low',
    temp_min_c: 10,
    temp_max_c: 35,
    soil_fr: 'Mélange pour cactées et succulentes.',
    fertilize_fr: 'Deux fois en été, engrais pour cactées.',
    fertilize_every_days: 60,
    repot_every_years: 3,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Vomissements et diarrhée.',
    difficulty: 'easy',
    tips_fr: 'Lui donner la fenêtre la plus ensoleillée de la maison.',
  }),
  p({
    id: 'strelitzia-reginae',
    latin_name: 'Strelitzia reginae',
    common_names_fr: ['Oiseau de paradis', 'Strelitzia'],
    common_names_en: ['Bird of paradise'],
    family: 'Strelitziaceae',
    light: 'direct',
    water_every_days_summer: 6,
    water_every_days_winter: 12,
    water_notes_fr: 'Arroser régulièrement en été, laisser sécher le dessus en hiver.',
    humidity: 'medium',
    temp_min_c: 12,
    temp_max_c: 30,
    soil_fr: 'Terreau riche et drainant.',
    fertilize_fr: 'Toutes les 2 semaines d’avril à septembre.',
    fertilize_every_days: 14,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Troubles digestifs légers.',
    difficulty: 'medium',
    tips_fr:
      'Les feuilles fendues sont naturelles. Beaucoup de lumière pour espérer une floraison.',
  }),
  p({
    id: 'philodendron-hederaceum',
    latin_name: 'Philodendron hederaceum',
    common_names_fr: ['Philodendron grimpant'],
    common_names_en: ['Heartleaf philodendron'],
    family: 'Araceae',
    light: 'medium',
    water_every_days_summer: 7,
    water_every_days_winter: 12,
    water_notes_fr: 'Laisser sécher le premier tiers du pot.',
    humidity: 'medium',
    temp_min_c: 15,
    temp_max_c: 30,
    soil_fr: 'Terreau pour plantes vertes avec écorce.',
    fertilize_fr: 'Une fois par mois au printemps et en été.',
    fertilize_every_days: 30,
    repot_every_years: 2,
    pet_toxic: 'yes',
    pet_toxic_note_fr: 'Irritation buccale, vomissements.',
    difficulty: 'easy',
    tips_fr: 'Parfait en suspension ou sur une étagère, il retombe joliment.',
  }),
  p({
    id: 'phalaenopsis',
    latin_name: 'Phalaenopsis',
    common_names_fr: ['Orchidée papillon', 'Phalaenopsis'],
    common_names_en: ['Moth orchid'],
    family: 'Orchidaceae',
    light: 'bright_indirect',
    water_every_days_summer: 7,
    water_every_days_winter: 12,
    water_notes_fr:
      'Tremper le pot 10 minutes quand les racines deviennent argentées, puis bien égoutter.',
    humidity: 'medium',
    temp_min_c: 16,
    temp_max_c: 28,
    soil_fr: 'Substrat d’écorce pour orchidées.',
    fertilize_fr: 'Engrais orchidées un arrosage sur trois.',
    fertilize_every_days: 21,
    repot_every_years: 2,
    pet_toxic: 'no',
    difficulty: 'medium',
    tips_fr: 'Une baisse de température la nuit à l’automne aide à relancer la floraison.',
  }),
  p({
    id: 'hoya-carnosa',
    latin_name: 'Hoya carnosa',
    common_names_fr: ['Fleur de porcelaine', 'Hoya'],
    common_names_en: ['Wax plant'],
    family: 'Apocynaceae',
    light: 'bright_indirect',
    water_every_days_summer: 10,
    water_every_days_winter: 20,
    water_notes_fr: 'Laisser sécher presque entièrement entre deux arrosages.',
    humidity: 'medium',
    temp_min_c: 12,
    temp_max_c: 30,
    soil_fr: 'Mélange drainant écorce + perlite + terreau.',
    fertilize_fr: 'Une fois par mois au printemps et en été.',
    fertilize_every_days: 30,
    repot_every_years: 3,
    pet_toxic: 'no',
    difficulty: 'easy',
    tips_fr: 'Ne pas couper les anciennes hampes florales : elles refleurissent.',
  }),
  p({
    id: 'peperomia-obtusifolia',
    latin_name: 'Peperomia obtusifolia',
    common_names_fr: ['Pépéromia'],
    common_names_en: ['Baby rubber plant'],
    family: 'Piperaceae',
    light: 'medium',
    water_every_days_summer: 9,
    water_every_days_winter: 16,
    water_notes_fr: 'Feuilles charnues : laisser sécher le terreau aux deux tiers.',
    humidity: 'medium',
    temp_min_c: 15,
    temp_max_c: 28,
    soil_fr: 'Terreau léger et drainant.',
    fertilize_fr: 'Une fois par mois au printemps et en été, à demi-dose.',
    fertilize_every_days: 30,
    repot_every_years: 3,
    pet_toxic: 'no',
    difficulty: 'easy',
    tips_fr: 'Compacte et peu exigeante, idéale pour un bureau.',
  }),
];

const out = new URL('../../assets/catalog/catalog.json', import.meta.url);
writeFileSync(out, JSON.stringify({ version: 1, plants }, null, 2) + '\n');
console.log(`Wrote ${plants.length} plants`);
